### ISSUE TITLE
Error on multiplayer: "Minecraft - Failed to handle packet: java.lang.NullPointerException: Cannot read field "fontRenderer" because "mc" is null"

### ISSUE THREAD

**Issue by SamuelDeboni** [MartinSVK12/energyapi#2]
When you try to open any GUI implemented by EnergyAPI on multiplayer, I get the following error:

```
2023-10-09 10:12:20 WARN  Minecraft - Failed to handle packet: java.lang.NullPointerException: Cannot read field "fontRenderer" because "mc" is null
java.lang.NullPointerException: Cannot read field "fontRenderer" because "mc" is null
	at net.minecraft.client.gui.GuiTooltip.<init>(GuiTooltip.java:25)
	at net.minecraft.client.gui.GuiContainer.<init>(GuiContainer.java:54)
	at sunsetsatellite.energyapi.template.gui.GuiGenerator.<init>(GuiGenerator.java:19)
	at sunsetsatellite.energyapi.template.blocks.BlockGenerator.blockActivated(BlockGenerator.java:31)
	at net.minecraft.server.world.ItemInWorldManager.activateBlockOrUseItem(ItemInWorldManager.java:171)
	at net.minecraft.server.net.handler.NetServerHandler.handlePlace(NetServerHandler.java:420)
	at net.minecraft.core.net.packet.Packet15Place.processPacket(Packet15Place.java:80)
	at net.minecraft.core.net.NetworkManager.processReadPackets(NetworkManager.java:214)
	at net.minecraft.server.net.handler.NetServerHandler.handlePackets(NetServerHandler.java:113)
	at net.minecraft.server.net.NetworkListenThread.handleNetworkListenThread(NetworkListenThread.java:83)
	at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:541)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:439)
	at net.minecraft.server.net.thread.ThreadServerApplication.run(ThreadServerApplication.java:21)
```

**Comment by MartinSVK12** [comment]
Fixed in 1.1.7
